-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 14:41:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema projectexam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectexam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectexam` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`klanten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klanten` (
  `idklanten` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idklanten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bedrijf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bedrijf` (
  `idbedrijf` INT(11) NOT NULL AUTO_INCREMENT,
  `naambedrijf` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `eigennaar` VARCHAR(45) NULL,
  `website` VARCHAR(200) NULL,
  `kvk` VARCHAR(120) NULL,
  `btwnummer` VARCHAR(120) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idbedrijf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bedrijf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bedrijf` (
  `idbedrijf` INT(11) NOT NULL AUTO_INCREMENT,
  `naambedrijf` VARCHAR(45) NULL,
  `adres` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `eigennaar` VARCHAR(45) NULL,
  `website` VARCHAR(200) NULL,
  `kvk` VARCHAR(120) NULL,
  `btwnummer` VARCHAR(120) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idbedrijf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maaltijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maaltijd` (
  `idmaaltijd` INT(20) NOT NULL,
  `etennaam` VARCHAR(45) NULL,
  `restaurantnaam` VARCHAR(45) NULL,
  `prijs` VARCHAR(45) NULL,
  `ingredienten` VARCHAR(500) NULL,
  `bedrijf_idbedrijf` INT(11) NOT NULL,
  PRIMARY KEY (`idmaaltijd`),
  INDEX `fk_maaltijd_bedrijf_idx` (`bedrijf_idbedrijf` ASC) VISIBLE,
  CONSTRAINT `fk_maaltijd_bedrijf`
    FOREIGN KEY (`bedrijf_idbedrijf`)
    REFERENCES `mydb`.`bedrijf` (`idbedrijf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `projectexam` ;

-- -----------------------------------------------------
-- Table `projectexam`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectexam`.`accounts` (
  `idaccount` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `isADMIN` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectexam`.`gegevens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectexam`.`gegevens` (
  `idgegevens` INT(11) NOT NULL AUTO_INCREMENT,
  `lengte` INT(11) NULL DEFAULT NULL,
  `kg` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `datum` DATE NULL DEFAULT NULL,
  `accounts_idaccount` INT(11) NOT NULL,
  PRIMARY KEY (`idgegevens`),
  INDEX `fk_gegevens_accounts_idx` (`accounts_idaccount` ASC) VISIBLE,
  CONSTRAINT `fk_gegevens_accounts`
    FOREIGN KEY (`accounts_idaccount`)
    REFERENCES `projectexam`.`accounts` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
