-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 23:48:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema id19625817_project_bezorgthuis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id19625817_project_bezorgthuis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id19625817_project_bezorgthuis` DEFAULT CHARACTER SET utf8 ;
USE `id19625817_project_bezorgthuis` ;

-- -----------------------------------------------------
-- Table `id19625817_project_bezorgthuis`.`klanten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id19625817_project_bezorgthuis`.`klanten` ;

CREATE TABLE IF NOT EXISTS `id19625817_project_bezorgthuis`.`klanten` (
  `idklanten` INT NOT NULL,
  `naam` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idklanten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id19625817_project_bezorgthuis`.`bedrijf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id19625817_project_bezorgthuis`.`bedrijf` ;

CREATE TABLE IF NOT EXISTS `id19625817_project_bezorgthuis`.`bedrijf` (
  `kvk` INT(120) NOT NULL,
  `naambedrijf` VARCHAR(45) NULL,
  `stad` VARCHAR(45) NULL,
  `straat` VARCHAR(45) NULL,
  `huisnummer` INT(10) NULL,
  `website` VARCHAR(200) NULL,
  `contacttelefoon` INT(50) NULL,
  `contactemail` VARCHAR(200) NULL,
  `btwnummer` VARCHAR(120) NULL,
  `password` VARCHAR(500) NULL,
  PRIMARY KEY (`kvk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id19625817_project_bezorgthuis`.`bedrijf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id19625817_project_bezorgthuis`.`bedrijf` ;

CREATE TABLE IF NOT EXISTS `id19625817_project_bezorgthuis`.`bedrijf` (
  `kvk` INT(120) NOT NULL,
  `naambedrijf` VARCHAR(45) NULL,
  `stad` VARCHAR(45) NULL,
  `straat` VARCHAR(45) NULL,
  `huisnummer` INT(10) NULL,
  `website` VARCHAR(200) NULL,
  `contacttelefoon` INT(50) NULL,
  `contactemail` VARCHAR(200) NULL,
  `btwnummer` VARCHAR(120) NULL,
  `password` VARCHAR(500) NULL,
  PRIMARY KEY (`kvk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id19625817_project_bezorgthuis`.`klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id19625817_project_bezorgthuis`.`klant` ;

CREATE TABLE IF NOT EXISTS `id19625817_project_bezorgthuis`.`klant` (
  `idklant` INT(255) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(50) NULL,
  `email` VARCHAR(150) NULL,
  `stad` VARCHAR(50) NULL,
  `huisnummer` VARCHAR(45) NULL,
  `straat` VARCHAR(45) NULL,
  `password` VARCHAR(500) NULL,
  PRIMARY KEY (`idklant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id19625817_project_bezorgthuis`.`gerechten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id19625817_project_bezorgthuis`.`gerechten` ;

CREATE TABLE IF NOT EXISTS `id19625817_project_bezorgthuis`.`gerechten` (
  `idgerechten` INT(255) NOT NULL AUTO_INCREMENT,
  `etennaam` VARCHAR(45) NULL,
  `prijs` INT NULL,
  `categorie` VARCHAR(100) NULL,
  `bedrijf_kvk` INT(120) NOT NULL,
  PRIMARY KEY (`idgerechten`),
  INDEX `fk_gerechten_bedrijf1_idx` (`bedrijf_kvk` ASC),
  CONSTRAINT `fk_gerechten_bedrijf1`
    FOREIGN KEY (`bedrijf_kvk`)
    REFERENCES `id19625817_project_bezorgthuis`.`bedrijf` (`kvk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id19625817_project_bezorgthuis`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id19625817_project_bezorgthuis`.`orders` ;

CREATE TABLE IF NOT EXISTS `id19625817_project_bezorgthuis`.`orders` (
  `idorders` INT NOT NULL,
  `item` VARCHAR(45) NULL,
  `hoeveel` VARCHAR(45) NULL,
  `orderscol` VARCHAR(45) NULL,
  `klant_idklant` INT(255) NOT NULL,
  PRIMARY KEY (`idorders`),
  INDEX `fk_orders_klant1_idx` (`klant_idklant` ASC),
  CONSTRAINT `fk_orders_klant1`
    FOREIGN KEY (`klant_idklant`)
    REFERENCES `id19625817_project_bezorgthuis`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
